### ISSUE TITLE
Unable to find module

### ISSUE THREAD

**Issue by rlepinski** [urbanairship/titanium-module#1]
@chmiiller - http://stackoverflow.com/questions/36206479/push-notifications-on-android-5-not-delivered-when-app-in-background-titanium

Want to move the conversation here.

So build the plugin successfully, installed the module, and the app fails to find the module?

**Comment by rlepinski** [comment]
Could you post how you installed the module? Also, try rebuilding it. I modified the build.xml.

**Comment by rlepinski** [comment]
You can download the pre-built plugins here https://bintray.com/urbanairship/titanium/titanium-module/_latestVersion

**Comment by chmiiller** [comment]
going to try it

**Comment by chmiiller** [comment]
Hi @rlepinski didn't work =/
To install the module I've put it inside a "module" folder in my project. Then in the tiapp.xml I added the tag pointing to the module and require it in the app.js.
Take a look at the attachments =)
![app](https://cloud.githubusercontent.com/assets/1013632/14599373/410fc9ba-0557-11e6-9d3b-76990e377423.png)
![folder](https://cloud.githubusercontent.com/assets/1013632/14599374/41604020-0557-11e6-9c1c-07b2c206eb21.png)
![tiapp](https://cloud.githubusercontent.com/assets/1013632/14599375/41611842-0557-11e6-8353-5ca238ffd8af.png)

**Comment by chmiiller** [comment]
This is the error message...

```
[WARN]  Could not find a valid Titanium module id=com.urbanairship version=latest platform=android deploy-type=development
[ERROR] Could not find all required Titanium Modules:
[ERROR]    id: com.urbanairship  version: latest     platform: android   deploy-type: development
```

Tried to create another project and to clean it as well, it just doesn't build. 
Is it working for you?

**Comment by rlepinski** [comment]
I was only installing the module by unzipping it in the global location. Dropping the modules in the "modules" directory reproduced your error. Looking into it.

Thanks :)

**Comment by chmiiller** [comment]
hun, good to know! I will try tomorrow then (18:30 here already)
Thanks for letting me know

**Comment by rlepinski** [comment]
Ok, so if i unzip the module so the output is `<app directory>/modules/android/com.urbanairship/...` it builds. I cant seem to find an example of just dropping the zip files into the modules directory.

**Comment by rlepinski** [comment]
Your test file should look like:

```
var UrbanAirship = require('com.urbanairship');
UrbanAirship.userNotificationsEnabled = true;

UrbanAirship.addEventListener(UrbanAirship.EVENT_CHANNEL_UPDATED, onPushReceived);
UrbanAirship.addEventListener(UrbanAirship.EVENT_PUSH_RECEIVED, onChannelUpdated);

function onPushReceived(e) {
    console.log('************* onPushReceived: ' + JSON.stringify(e));
    alert(JSON.stringify(e));
}

function onChannelUpdated(e) {
    console.log('************* onChannelUpdated: ' + JSON.stringify(e));
}
```

This is a new module from scratch so the api is going to differ a bit from the ti.urbanairship module.

**Comment by chmiiller** [comment]
Sorry about that. It was not working with Titanium 5.1.2.GA. If I test it with 5.2.2.GA it works perfectly!
Thank you so much!

**Comment by wackyapps** [comment]
Yes, Installing new SDK such as for me 5.2.3 works. And module not found error isgone now.

I downloaded and manually installed 5.2.3 SDK manually from this link: http://builds.appcelerator.com/#5_2_X

Thanks!
