### ISSUE TITLE
when click on the notification and app is closed/in background the App crashes

### ISSUE THREAD

**Issue by e3bmo3ty** [urbanairship/titanium-module#10]
# when receive a notification and the Application is closed/in background, it opens the crash in once it launches and dosen't open again!

android version : 5.1.1
tianuium SDK version : 5.2.2.GA

**Comment by rlepinski** [comment]
@e3bmo3ty Do you have any crash logs?

**Comment by rlepinski** [comment]
Please reopen if you still have the issue.
