### ISSUE TITLE
Unable to get the data from push notification when the application was launched

### ISSUE THREAD

**Issue by ainne10x29** [urbanairship/titanium-module#17]
I am trying to get the tags I have set in the Message I pushed on my device using the following codes:
var notificationLaunchApp = UrbanAirship.getLaunchNotification(true);
if (notificationLaunchApp.message !== undefined) {
    onPushReceived(notificationLaunchApp);
}

I can get the data if the application was resumed or if the application was launched from background. But if the app is totally close and I used the notification to open it. The data is always blank or empty: onPushReceived deeplink data: {"message":"","extras":{}}

I am trying to get the same value I am getting from resumed activity

onPushReceived deeplink data: {"message":"Push notification test,"extras":{"^+t":["tagtagtagIneed"],"^d":"myapp://"}}

**Comment by rlepinski** [comment]
Android or iOS? We will look into it.

**Comment by ainne10x29** [comment]
iOS. Not yet tested in Android.. I'll also try it on Android..

**Comment by rlepinski** [comment]
@ainne10x29 what iOS version are you testing against?

**Comment by rlepinski** [comment]
I was able to reproduce the issue, I believe https://github.com/urbanairship/titanium-module/pull/19 fixes it.

**Comment by rlepinski** [comment]
Could you try out and verify your issue is fixed in the 2.0.2 build before I release it? 
[com.urbanairship-iphone-2.0.2.zip](https://github.com/urbanairship/titanium-module/files/576816/com.urbanairship-iphone-2.0.2.zip)

**Comment by ainne10x29** [comment]
@rlepinski - I am having the issue of UserNotification.framework. As per checking, this framework is for iOS10 and can only be use with xCode8. Is there any workaround? :)

**Comment by ainne10x29** [comment]
@rlepinski - Done with it. I saw what you modified in 2.0.2 and modified it instead in version 1.3.0. Your fix really works. Thanks for your help.

**Comment by rlepinski** [comment]
@ainne10x29 Awesome, glad it works for you!
