### ISSUE TITLE
problems with facebook module in android 

### ISSUE THREAD

**Issue by addieljuarez** [urbanairship/titanium-module#24]
when I add the urban airship module and later I add the facebook module leave this message in console 

ERROR] :  Failed to package application:
[ERROR] :  
[ERROR] :  warning: string 'com_facebook_device_auth_instructions' has no default translation.
[ERROR] :  warning: string 'com_facebook_image_download_unknown_error' has no default translation.
[ERROR] :  warning: string 'com_facebook_internet_permission_error_message' has no default translation.
[ERROR] :  warning: string 'com_facebook_internet_permission_error_title' has no default translation.
[ERROR] :  warning: string 'com_facebook_like_button_liked' has no default translation.
[ERROR] :  warning: string 'com_facebook_like_button_not_liked' has no default translation.
[ERROR] :  warning: string 'com_facebook_loading' has no default translation.
[ERROR] :  warning: string 'com_facebook_loginview_cancel_action' has no default translation.
[ERROR] :  warning: string 'com_facebook_loginview_log_in_button' has no default translation.
[ERROR] :  warning: string 'com_facebook_loginview_log_in_button_long' has no default translation.
[ERROR] :  warning: string 'com_facebook_loginview_log_out_action' has no default translation.
[ERROR] :  warning: string 'com_facebook_loginview_log_out_button' has no default translation.
[ERROR] :  warning: string 'com_facebook_loginview_logged_in_as' has no default translation.
[ERROR] :  warning: string 'com_facebook_loginview_logged_in_using_facebook' has no default translation.
[ERROR] :  warning: string 'com_facebook_send_button_text' has no default translation.
[ERROR] :  warning: string 'com_facebook_share_button_text' has no default translation.
[ERROR] :  warning: string 'com_facebook_tooltip_default' has no default translation.
[ERROR] :  warning: string 'messenger_send_button_text' has no default translation.
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/layout/com_facebook_device_auth_dialog_fragment.xml:56: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/com_facebook_share_button_text_color').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/layout/com_facebook_device_auth_dialog_fragment.xml:70: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/com_facebook_device_auth_text').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/layout/com_facebook_device_auth_dialog_fragment.xml:88: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/com_facebook_device_auth_text').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/layout/com_facebook_device_auth_dialog_fragment.xml:117: error: Error: No resource found that matches the given name (at 'textColor' with value '@color/com_facebook_device_auth_text').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/layout/com_facebook_tooltip_bubble.xml:44: error: Error: No resource found that matches the given name (at 'style' with value '@style/tooltip_bubble_text').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/layout/messenger_button_send_blue_large.xml:22: error: Error: No resource found that matches the given name (at 'style' with value '@style/MessengerButton.Blue.Large').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/layout/messenger_button_send_blue_large.xml:27: error: Error: No resource found that matches the given name (at 'style' with value '@style/MessengerButtonText.Blue.Large').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/layout/messenger_button_send_blue_small.xml:22: error: Error: No resource found that matches the given name (at 'style' with value '@style/MessengerButton.Blue.Small').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/layout/messenger_button_send_blue_small.xml:27: error: Error: No resource found that matches the given name (at 'style' with value '@style/MessengerButtonText.Blue.Small').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/layout/messenger_button_send_white_large.xml:22: error: Error: No resource found that matches the given name (at 'style' with value '@style/MessengerButton.White.Large').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/layout/messenger_button_send_white_large.xml:27: error: Error: No resource found that matches the given name (at 'style' with value '@style/MessengerButtonText.White.Large').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/layout/messenger_button_send_white_small.xml:22: error: Error: No resource found that matches the given name (at 'style' with value '@style/MessengerButton.White.Small').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/layout/messenger_button_send_white_small.xml:27: error: Error: No resource found that matches the given name (at 'style' with value '@style/MessengerButtonText.White.Small').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_auth_dialog_background.xml:24: error: Error: No resource found that matches the given name (at 'bottomLeftRadius' with value '@dimen/com_facebook_auth_dialog_corner_radius').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_auth_dialog_background.xml:24: error: Error: No resource found that matches the given name (at 'bottomRightRadius' with value '@dimen/com_facebook_auth_dialog_corner_radius').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_auth_dialog_background.xml:24: error: Error: No resource found that matches the given name (at 'topLeftRadius' with value '@dimen/com_facebook_auth_dialog_corner_radius_oversized').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_auth_dialog_background.xml:24: error: Error: No resource found that matches the given name (at 'topRightRadius' with value '@dimen/com_facebook_auth_dialog_corner_radius_oversized').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_auth_dialog_header_background.xml:23: error: Error: No resource found that matches the given name (at 'color' with value '@color/com_facebook_blue').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_auth_dialog_header_background.xml:24: error: Error: No resource found that matches the given name (at 'topLeftRadius' with value '@dimen/com_facebook_auth_dialog_corner_radius').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_auth_dialog_header_background.xml:24: error: Error: No resource found that matches the given name (at 'topRightRadius' with value '@dimen/com_facebook_auth_dialog_corner_radius').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_background.xml:26: error: Error: No resource found that matches the given name (at 'radius' with value '@dimen/com_facebook_button_corner_radius').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_background.xml:27: error: Error: No resource found that matches the given name (at 'color' with value '@color/com_facebook_button_background_color_focused_disabled').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_background.xml:33: error: Error: No resource found that matches the given name (at 'radius' with value '@dimen/com_facebook_button_corner_radius').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_background.xml:34: error: Error: No resource found that matches the given name (at 'color' with value '@color/com_facebook_button_background_color_disabled').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_background.xml:39: error: Error: No resource found that matches the given name (at 'radius' with value '@dimen/com_facebook_button_corner_radius').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_background.xml:40: error: Error: No resource found that matches the given name (at 'color' with value '@color/com_facebook_button_background_color_focused').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_background.xml:41: error: Error: No resource found that matches the given name (at 'color' with value '@color/com_facebook_button_border_color_focused').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_background.xml:49: error: Error: No resource found that matches the given name (at 'radius' with value '@dimen/com_facebook_button_corner_radius').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_background.xml:50: error: Error: No resource found that matches the given name (at 'color' with value '@color/com_facebook_button_background_color_pressed').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_background.xml:55: error: Error: No resource found that matches the given name (at 'radius' with value '@dimen/com_facebook_button_corner_radius').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_background.xml:56: error: Error: No resource found that matches the given name (at 'color' with value '@color/com_facebook_button_background_color').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_like_background.xml:25: error: Error: No resource found that matches the given name (at 'radius' with value '@dimen/com_facebook_button_corner_radius').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_like_background.xml:26: error: Error: No resource found that matches the given name (at 'color' with value '@color/com_facebook_button_background_color_pressed').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_like_background.xml:32: error: Error: No resource found that matches the given name (at 'radius' with value '@dimen/com_facebook_button_corner_radius').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_like_background.xml:33: error: Error: No resource found that matches the given name (at 'color' with value '@color/com_facebook_button_background_color_focused_disabled').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_like_background.xml:39: error: Error: No resource found that matches the given name (at 'radius' with value '@dimen/com_facebook_button_corner_radius').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_like_background.xml:40: error: Error: No resource found that matches the given name (at 'color' with value '@color/com_facebook_button_background_color_disabled').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_like_background.xml:45: error: Error: No resource found that matches the given name (at 'radius' with value '@dimen/com_facebook_button_corner_radius').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_like_background.xml:46: error: Error: No resource found that matches the given name (at 'color' with value '@color/com_facebook_button_background_color_focused').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_like_background.xml:51: error: Error: No resource found that matches the given name (at 'radius' with value '@dimen/com_facebook_button_corner_radius').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_like_background.xml:52: error: Error: No resource found that matches the given name (at 'color' with value '@color/com_facebook_button_background_color_selected').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_like_background.xml:57: error: Error: No resource found that matches the given name (at 'radius' with value '@dimen/com_facebook_button_corner_radius').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_like_background.xml:58: error: Error: No resource found that matches the given name (at 'color' with value '@color/com_facebook_button_background_color').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_login_silver_background.xml:25: error: Error: No resource found that matches the given name (at 'radius' with value '@dimen/com_facebook_button_corner_radius').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_login_silver_background.xml:26: error: Error: No resource found that matches the given name (at 'color' with value '@color/com_facebook_button_background_color_disabled').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_login_silver_background.xml:31: error: Error: No resource found that matches the given name (at 'radius' with value '@dimen/com_facebook_button_corner_radius').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_login_silver_background.xml:32: error: Error: No resource found that matches the given name (at 'color' with value '@color/com_facebook_button_login_silver_background_color_pressed').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_login_silver_background.xml:37: error: Error: No resource found that matches the given name (at 'radius' with value '@dimen/com_facebook_button_corner_radius').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_login_silver_background.xml:38: error: Error: No resource found that matches the given name (at 'color' with value '@color/com_facebook_button_login_silver_background_color').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_send_background.xml:26: error: Error: No resource found that matches the given name (at 'radius' with value '@dimen/com_facebook_button_corner_radius').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_send_background.xml:27: error: Error: No resource found that matches the given name (at 'color' with value '@color/com_facebook_button_background_color_focused_disabled').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_send_background.xml:33: error: Error: No resource found that matches the given name (at 'radius' with value '@dimen/com_facebook_button_corner_radius').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_send_background.xml:34: error: Error: No resource found that matches the given name (at 'color' with value '@color/com_facebook_button_background_color_disabled').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_send_background.xml:39: error: Error: No resource found that matches the given name (at 'radius' with value '@dimen/com_facebook_button_corner_radius').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_send_background.xml:40: error: Error: No resource found that matches the given name (at 'color' with value '@color/com_facebook_button_background_color_focused').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_send_background.xml:41: error: Error: No resource found that matches the given name (at 'color' with value '@color/com_facebook_button_border_color_focused').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_send_background.xml:50: error: Error: No resource found that matches the given name (at 'color' with value '@color/com_facebook_button_send_background_color_pressed').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/drawable/com_facebook_button_send_background.xml:56: error: Error: No resource found that matches the given name (at 'color' with value '@color/com_facebook_button_send_background_color').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/color/com_facebook_button_text_color.xml:22: error: Error: No resource found that matches the given name (at 'color' with value '@color/com_facebook_blue').
[ERROR] :  
[ERROR] :  /Users/addieljuarez/Documents/Appcelerator_Studio_Workspace/devVerifiKapp/build/android/res/color/com_facebook_send_button_text_color.xml:22: error: Error: No resource found that matches the given name (at 'color' with value '@color/com_facebook_messenger_blue').

Operating System
  Name                        = Mac OS X
  Version                     = 10.12.4
  Architecture                = 64bit
  # CPUs                      = 8
  Memory                      = 16.0GB

Node.js
  Node.js Version             = 6.10.1
  npm Version                 = 3.10.10

Appcelerator CLI
  Installer                   = 4.2.9
  Core Package                = 6.2.1

Titanium CLI
  CLI Version                 = 5.0.13
  node-appc Version           = 0.2.41

**Comment by rlepinski** [comment]
Thanks for the report. Could you link to the Facebook module you are using?
