### ISSUE TITLE
Problem with verifying compiled package

### ISSUE THREAD

**Issue by MShel** [urbanairship/titanium-module#29]
Hello,

I'm trying to prepare a build for production and when I try to submit to iTunes it comes back with following error:

iTunes Store operation failed.
Invalid Bundle Structure - The binary file '../modules/com.urbanairship/AirshipResources.bundle/AirshipResources' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure.

appc ti --version
5.0.14

appc --version
7.0.2

xcodebuild -version
Xcode 8.3.3

sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1212

Any help would be greatly appreciated

**Comment by spencersokol** [comment]
Is there a solution to this? I'm running into the same issue.

**Comment by marc-scig** [comment]
Hey there, sorry you're experiencing this. We're looking into it. Can you share your platform info, including the module version?

**Comment by marc-scig** [comment]
Hi all, quick update. It looks like when we updated to Titanium 7.0 it caused some problems with our AirshipResources bundle, which otherwise works fine in the SDK. We have a workaround, and should have an updated module for you to try within the next day. Thanks for your patience and for letting us know.

**Comment by marc-scig** [comment]
@MShel @spencersokol 4.0.1 is up on bintray. This should fix the problem with app store submissions but keep us posted if you have any further issues.

**Comment by spencersokol** [comment]
Thank you!
