### ISSUE TITLE
issue while building the Android app with titanium module

### ISSUE THREAD

**Issue by ersimarpreetsingh** [urbanairship/titanium-module#36]
I have been trying to run the command
`appc run -p android -T device`

and here is the code for my project
[https://github.com/ersimarpreetsingh/UrbanAirshipTitaniumDemo](https://github.com/ersimarpreetsingh/UrbanAirshipTitaniumDemo)

it is giving some gradle errors related to Urban Airship Module (I am using v 5.0.2)

The error I am getting is:

[INFO] [GRADLE] > Task :app:createDebugCompatibleScreenManifests
[INFO] [GRADLE] > Task :app:mergeDebugResources
[INFO] [GRADLE]
[ERROR] [GRADLE] D:\Programming\Titanium\newapp.yofima\build\android\app\src\debug\AndroidManifest.xml:71:13-72 Error:
[ERROR] [GRADLE] Attribute activity#com.urbanairship.CoreActivity@theme value=(@android:style/Theme.Translucent.NoTitleBar) from [:lib.com.urbanairship] AndroidManifest.xml:71:13-72
[ERROR] [GRADLE] is also present at [urbanairship-core-9.7.1.aar] AndroidManifest.xml:32:13-59 value=(@android:style/Theme.NoDisplay).
[ERROR] [GRADLE] Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:69:9-71:75 to override.
[ERROR] [GRADLE] D:\Programming\Titanium\newapp.yofima\build\android\app\src\debug\AndroidManifest.xml:78:13-72 Error:
[ERROR] [GRADLE] Attribute activity#com.urbanairship.util.HelperActivity@theme value=(@android:style/Theme.Translucent.NoTitleBar) from [:lib.com.urbanairship] AndroidManifest.xml:78:13-72
[ERROR] [GRADLE] is also present at [urbanairship-core-9.7.1.aar] AndroidManifest.xml:43:13-63 value=(@style/UrbanAirship.HelperActivity).[ERROR] [GRADLE] Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:76:9-82:20 to override.
[INFO] [GRADLE] > Task :app:processDebugManifest FAILED
[INFO] [GRADLE]
[INFO] [GRADLE] See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
[INFO] [GRADLE]
[ERROR] [GRADLE]
[ERROR] [GRADLE] FAILURE: Build failed with an exception.
[ERROR] [GRADLE]
[ERROR] [GRADLE] * What went wrong:
[ERROR] [GRADLE] Execution failed for task ':app:processDebugManifest'.
[ERROR] [GRADLE] > Manifest merger failed with multiple errors, see logs
[ERROR] [GRADLE]
[ERROR] [GRADLE] * Try:
[ERROR] [GRADLE] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[ERROR] [GRADLE]
[ERROR] [GRADLE] * Get more help at https://help.gradle.org
[ERROR] [GRADLE]
[ERROR] [GRADLE] BUILD FAILED in 40s
[INFO] [GRADLE] 20 actionable tasks: 20 executed
[ERROR] "gradlew" tool returned exit code: 1

**Comment by rlepinski** [comment]
Looks like you are using the newer version of Titanium with Gradle support. We have not yet updated the module to support the new version of Titanium, but we are planning an update in the near future.

**Comment by ersimarpreetsingh** [comment]
I was just curious If there was some fixed timeline for the update as I have been using it in one of my projects?

I am also facing issue when adding the module to iOS. The build got successful but it is not getting to the TestFlight instead I am getting an email from Apple which says:

Dear Developer,

> We identified one or more issues with a recent delivery for your app, "<AppName> 1.0.0 (1.0.0). Please correct the following issues, then upload again.
> 
> ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).
> 
> Best regards,
> 
> The App Store Team

**Comment by rlepinski** [comment]
We are working on it right now. I don't have an exact timeline but we will do a release shortly after we get iOS updated to an SDK version that does not use UIWebView. We are working on it now.

**Comment by rlepinski** [comment]
Should be fixed in 6.0.0
