### ISSUE TITLE
Problem with Android Build after Airship 6.0.0 update

### ISSUE THREAD

**Issue by ersimarpreetsingh** [urbanairship/titanium-module#42]
# Preliminary Info

### What Airship dependencies are you using?
titanium-module (Airship 6.0.0)

### What are the versions of any relevant development tools you are using?
Appcelerator 8.0.0 and  Titanium SDK 9.0.2.GA

# Report

### What unexpected behavior are you seeing?
I am building the app by running the command
`appc run -p android -T Device`
The app is getting installed on device successfully but when I am running the app I am getting these errors in the Terminal.
https://gist.github.com/ersimarpreetsingh/dcc36b72106eb8d2ab1cc38e157d7b0e

### What are the steps to reproduce the unexpected behavior?
Source code for demo app https://github.com/ersimarpreetsingh/UrbanAirshipTitaniumDemo
run command 
`appc build -p android -T device`

### Do you have logging for the issue?
https://gist.github.com/ersimarpreetsingh/dcc36b72106eb8d2ab1cc38e157d7b0e

**Comment by rlepinski** [comment]
6.0.0 we had to drop GCM and instead switched to FCM. I should of noted that in the changelog. It doesnt mean much, but you do need to copy the google-services.json file from the firebase dashboard into `platform/android/google-services.json`.

**Comment by ersimarpreetsingh** [comment]
@rlepinski when I place the file into platform/android/google-service.json and run

`appc run -p android -T device`

It deletes the file from that directory and still gives the same error. I also tried adding a dependency to build.gradle at the app and building it manually through Android Studio but still no success.

A little help here should be appreciated.
