### ISSUE TITLE
 Unable to register with FCM Android 6.0.0

### ISSUE THREAD

**Issue by emajoe** [urbanairship/titanium-module#51]
# Preliminary Info

### What Airship dependencies are you using?
Android 6.0.0

### What are the versions of any relevant development tools you are using?
Ti SDK 9.0.2 

# Report

### What unexpected behavior are you seeing?
App crashes upon opening and unable to register with FCM.

### What is the expected behavior?
Not crashing and register with FCM

### What are the steps to reproduce the unexpected behavior?
Build and run the app on a device. google-services.json file is included. Error appears to be related to play services.

### Do you have logging for the issue?
https://gist.github.com/emajoe/ad9bf9936a76c1c04fa4c38f48c4dfba

**Comment by rlepinski** [comment]
Do you still have the ti.playservices installed? If so you should remove it, its not a great way to install play services when you have access to gradle. https://github.com/appcelerator-modules/ti.playservices/blob/master/android/timodule.xml#L7

**Comment by marc-scig** [comment]
What version of google play services do you have installed on your device/emulator?

**Comment by emajoe** [comment]
@rlepinski I do not have that module installed.
@marc-scig I'm using a google pixel XL with Android 10

**Comment by marc-scig** [comment]
Good to know, but what version of google play services is installed?

**Comment by marc-scig** [comment]
Also worth asking, does this only happen on the device, or does it also happen in the emulator as well?

**Comment by emajoe** [comment]
@marc-scig google play v20.21.17 on the device.  I get the same error on the emulator as well

**Comment by rlepinski** [comment]
@emajoe I am pretty sure you have another plugin or setting that is overriding the google services version in the manifest, but I am not sure the best way to figure out where its coming from.

Please provide:
- list of plugins you are using
- any manifest entries in your tiapp.xml
- the manifest in `build/android/AndroidManifest.xml`
- the build-manifest.json file

**Comment by emajoe** [comment]
@rlepinski Here is the requested info: https://gist.github.com/emajoe/0a130d819a5bd2ea7eea5c42d110e659

**Comment by rlepinski** [comment]
https://github.com/appcelerator-modules/ti.map/blob/master/android/timodule.xml#L12
https://github.com/appcelerator-modules/ti.playservices/blob/master/android/timodule.xml#L8

I am not 100% if thats the issue, but I am pretty sure it is. Ill try to reproduce later today. For now could you remove the maps module to see if it works?

**Comment by emajoe** [comment]
I removed Ti.maps and still received the same error

`ERROR] E/EMA - UALib: Unable to register with FCM.
[ERROR] E/EMA - UALib: java.lang.IllegalStateException: The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 12451000 but found 10260000.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
[ERROR] E/EMA - UALib: 	at com.google.android.gms.common.GooglePlayServicesUtilLight.isGooglePlayServicesAvailable(com.google.android.gms:play-services-basement@@17.2.1:19)
[ERROR] E/EMA - UALib: 	at com.google.android.gms.common.GoogleApiAvailabilityLight.isGooglePlayServicesAvailable(com.google.android.gms:play-services-basement@@17.2.1:5)
[ERROR] E/EMA - UALib: 	at com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(com.google.android.gms:play-services-base@@17.2.1:96)
[ERROR] E/EMA - UALib: 	at com.google.android.gms.common.GoogleApiAvailabilityLight.isGooglePlayServicesAvailable(com.google.android.gms:play-services-basement@@17.2.1:3)
[ERROR] E/EMA - UALib: 	at com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(com.google.android.gms:play-services-base@@17.2.1:95)
[ERROR] E/EMA - UALib: 	at com.urbanairship.google.GooglePlayServicesUtilWrapper.isGooglePlayServicesAvailable(GooglePlayServicesUtilWrapper.java:27)
[ERROR] E/EMA - UALib: 	at com.urbanairship.google.PlayServicesUtils.isGooglePlayServicesAvailable(PlayServicesUtils.java:94)
[ERROR] E/EMA - UALib: 	at com.urbanairship.push.fcm.FcmPushProvider.isAvailable(FcmPushProvider.java:82)
[ERROR] E/EMA - UALib: 	at com.urbanairship.push.PushManager.performPushRegistration(PushManager.java:1006)
[ERROR] E/EMA - UALib: 	at com.urbanairship.push.PushManager.extendChannelRegistrationPayload(PushManager.java:320)
[ERROR] E/EMA - UALib: 	at com.urbanairship.push.PushManager.access$000(PushManager.java:53)
[ERROR] E/EMA - UALib: 	at com.urbanairship.push.PushManager$1.extend(PushManager.java:287)
[ERROR] E/EMA - UALib: 	at com.urbanairship.channel.AirshipChannel.getNextChannelRegistrationPayload(AirshipChannel.java:515)
[ERROR] E/EMA - UALib: 	at com.urbanairship.channel.AirshipChannel.onPerformJob(AirshipChannel.java:215)
[ERROR] E/EMA - UALib: 	at com.urbanairship.job.Job$1.run(Job.java:90)
[ERROR] E/EMA - UALib: 	at com.urbanairship.util.SerialExecutor$1.run(SerialExecutor.java:41)
[ERROR] E/EMA - UALib: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[ERROR] E/EMA - UALib: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[ERROR] E/EMA - UALib: 	at com.urbanairship.util.AirshipThreadFactory$1.run(AirshipThreadFactory.java:50)
[ERROR] E/EMA - UALib: 	at java.lang.Thread.run(Thread.java:919)`

**Comment by rlepinski** [comment]
Please run `grep -rnw . -e "google_play_services_version"` in your apps folder after you do an android build and report the output. That will hopefully report the version we are seeing. Also run `appc ti module list` so I can see the versions of your modules you have installed. It looks like only ti.maps and ti.adjust have a dependency on play services.

**Comment by emajoe** [comment]
Ti.adjust is the issue.  Thank you for all your help.  I'll close this out.

**Comment by rlepinski** [comment]
Woot!
