### ISSUE TITLE
getLaunchNotification blank on iOS when app is closed

### ISSUE THREAD

**Issue by TinyGiantDigital** [urbanairship/titanium-module#7]
When I send a push notification to a device where the app is closed (not open in multitasking) the app will open on clicking the notification however getLaunchNotification does not return the details of the push message. It simply returns {"message":"","extras":{}}

This affects iOS only (tested on iPhone 6, iOS 9.3).

getLaunchNotification works correctly when the app is in the background / multitasking.

Thanks for any help!

**Comment by rlepinski** [comment]
Thanks for reporting this. We will look into it today

**Comment by rlepinski** [comment]
@TinyGiantDigital It looks like the iOS notifies the app of the launch notification after the titanium `resume` event. If you use `resumed` the notification should be available.

**Comment by rlepinski** [comment]
@TinyGiantDigital My mistake, we had to do a small change to make `resumed` work. We will look into a different API in the future to make it easier to get the launch notificaiton at the right time. Thanks for reporting this!
